kind: Deployment
apiVersion: apps/v1
metadata:
  name: abcdeployment
spec:
  selector:
    matchLabels:
     app: sbi
  replicas: 4
  template:
    metadata:
      name: nginxpod
      labels:
        app: sbi
    spec:
     containers:
     - name: mycontainer
       image: nginx

